---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  # type: ClusterIP
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 1.2.3.4/32
  - 5.6.7.8/32
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana-ui
    protocol: TCP
  selector:
    app: grafana
